const countryList = [
  { nationality: 'Afghan', name: 'Afghanistan', code: 'AF' },
  { nationality: 'Albanian', name: 'Albania', code: 'AL' },
  { nationality: 'Algerian', name: 'Algeria', code: 'DZ' },
  { nationality: 'Andorran', name: 'AndorrA', code: 'AD' },
  { nationality: 'Angolan', name: 'Angola', code: 'AO' },
  { nationality: 'Antiguan and Barbudan', name: 'Antigua and Barbuda', code: 'AG' },
  { nationality: 'Argentine', name: 'Argentina', code: 'AR' },
  { nationality: 'Armenian', name: 'Armenia', code: 'AM' },
  { nationality: 'Australian', name: 'Australia', code: 'AU' },
  { nationality: 'Austrian', name: 'Austria', code: 'AT' },
  { nationality: 'Azerbaijani', name: 'Azerbaijan', code: 'AZ' },
  { nationality: 'Bahamian', name: 'Bahamas', code: 'BS' },
  { nationality: 'Bahraini', name: 'Bahrain', code: 'BH' },
  { nationality: 'Bangladeshi', name: 'Bangladesh', code: 'BD' },
  { nationality: 'Barbadian', name: 'Barbados', code: 'BB' },
  { nationality: 'Belarusian', name: 'Belarus', code: 'BY' },
  { nationality: 'Belgian', name: 'Belgium', code: 'BE' },
  { nationality: 'Belizean', name: 'Belize', code: 'BZ' },
  { nationality: 'Beninese', name: 'Benin', code: 'BJ' },
  { nationality: 'Bhutanese', name: 'Bhutan', code: 'BT' },
  { nationality: 'Bolivian', name: 'Bolivia', code: 'BO' },
  { nationality: 'Bosnian and Herzegovinian', name: 'Bosnia and Herzegovina', code: 'BA' },
  { nationality: 'Motswana', name: 'Botswana', code: 'BW' },
  { nationality: 'Brazilian', name: 'Brazil', code: 'BR' },
  { nationality: 'Bruneian', name: 'Brunei Darussalam', code: 'BN' },
  { nationality: 'Bulgarian', name: 'Bulgaria', code: 'BG' },
  { nationality: 'Burkinabé', name: 'Burkina Faso', code: 'BF' },
  { nationality: 'Burundian', name: 'Burundi', code: 'BI' },
  { nationality: 'Cambodian', name: 'Cambodia', code: 'KH' },
  { nationality: 'Cameroonian', name: 'Cameroon', code: 'CM' },
  { nationality: 'Canadian', name: 'Canada', code: 'CA' },
  { nationality: 'Central African', name: 'Central African Republic', code: 'CF' },
  { nationality: 'Chadian', name: 'Chad', code: 'TD' },
  { nationality: 'Chilean', name: 'Chile', code: 'CL' },
  { nationality: 'Chinese', name: 'China', code: 'CN' },
  { nationality: 'Colombian', name: 'Colombia', code: 'CO' },
  { nationality: 'Comorian', name: 'Comoros', code: 'KM' },
  { nationality: 'Congolese', name: 'Congo', code: 'CG' },
  { nationality: 'Congolese', name: 'The Democratic Republic of the Congo', code: 'CD' },
  { nationality: 'Costa Rican', name: 'Costa Rica', code: 'CR' },
  { nationality: 'Ivorian', name: 'Ivory Coast', code: 'CI' },
  { nationality: 'Croatian', name: 'Croatia', code: 'HR' },
  { nationality: 'Cuban', name: 'Cuba', code: 'CU' },
  { nationality: 'Cypriot', name: 'Cyprus', code: 'CY' },
  { nationality: 'Czech', name: 'Czech Republic', code: 'CZ' },
  { nationality: 'Danish', name: 'Denmark', code: 'DK' },
  { nationality: 'Djiboutian', name: 'Djibouti', code: 'DJ' },
  { nationality: 'Dominican', name: 'Dominica', code: 'DM' },
  { nationality: 'Dominican', name: 'Dominican Republic', code: 'DO' },
  { nationality: 'Ecuadorian', name: 'Ecuador', code: 'EC' },
  { nationality: 'Egyptian', name: 'Egypt', code: 'EG' },
  { nationality: 'Salvadoran', name: 'El Salvador', code: 'SV' },
  { nationality: 'Equatorial Guinean', name: 'Equatorial Guinea', code: 'GQ' },
  { nationality: 'Eritrean', name: 'Eritrea', code: 'ER' },
  { nationality: 'Estonian', name: 'Estonia', code: 'EE' },
  { nationality: 'Ethiopian', name: 'Ethiopia', code: 'ET' },
  { nationality: 'Fijian', name: 'Fiji', code: 'FJ' },
  { nationality: 'Finnish', name: 'Finland', code: 'FI' },
  { nationality: 'French', name: 'France', code: 'FR' },
  { nationality: 'Gabonese', name: 'Gabon', code: 'GA' },
  { nationality: 'Gambian', name: 'Gambia', code: 'GM' },
  { nationality: 'Georgian', name: 'Georgia', code: 'GE' },
  { nationality: 'German', name: 'Germany', code: 'DE' },
  { nationality: 'Ghanaian', name: 'Ghana', code: 'GH' },
  { nationality: 'Greek', name: 'Greece', code: 'GR' },
  { nationality: 'Grenadian', name: 'Grenada', code: 'GD' },
  { nationality: 'Guatemalan', name: 'Guatemala', code: 'GT' },
  { nationality: 'Equatorial Guinean', name: 'Guinea', code: 'GN' },
  { nationality: 'Bissau - Bissau-Guinean', name: 'Guinea-Bissau', code: 'GW' },
  { nationality: 'Guyanese', name: 'Guyana', code: 'GY' },
  { nationality: 'Haitian', name: 'Haiti', code: 'HT' },
  { nationality: 'Vatican', name: 'Vatican City', code: 'VA' },
  { nationality: 'Honduran', name: 'Honduras', code: 'HN' },
  { nationality: 'Hungarian', name: 'Hungary', code: 'HU' },
  { nationality: 'Icelander', name: 'Iceland', code: 'IS' },
  { nationality: 'Indian', name: 'India', code: 'IN' },
  { nationality: 'Indonesian', name: 'Indonesia', code: 'ID' },
  { nationality: 'Iranian', name: 'Islamic Republic Of Iran', code: 'IR' },
  { nationality: 'Iraqi', name: 'Iraq', code: 'IQ' },
  { nationality: 'Irish', name: 'Ireland', code: 'IE' },
  { nationality: 'Israeli', name: 'Israel', code: 'IL' },
  { nationality: 'Italian', name: 'Italy', code: 'IT' },
  { nationality: 'Jamaican', name: 'Jamaica', code: 'JM' },
  { nationality: 'Japanese', name: 'Japan', code: 'JP' },
  { nationality: 'Jordanian', name: 'Jordan', code: 'JO' },
  { nationality: 'Kazakhstani', name: 'Kazakhstan', code: 'KZ' },
  { nationality: 'Kenyan', name: 'Kenya', code: 'KE' },
  { nationality: 'I-Kiribati', name: 'Kiribati', code: 'KI' },
  { nationality: 'North Korea', name: 'North Korean', code: 'KP' },
  { nationality: 'South Korean', name: 'South Korea', code: 'KR' },
  { nationality: 'Kuwaiti', name: 'Kuwait', code: 'KW' },
  { nationality: 'Kyrgyzstani', name: 'Kyrgyzstan', code: 'KG' },
  { nationality: 'Laotian', name: 'Laos', code: 'LA' },
  { nationality: 'Latvian', name: 'Latvia', code: 'LV' },
  { nationality: 'Lebanese', name: 'Lebanon', code: 'LB' },
  { nationality: 'Mosotho', name: 'Lesotho', code: 'LS' },
  { nationality: 'Liberian', name: 'Liberia', code: 'LR' },
  { nationality: 'Libyan', name: 'Libya', code: 'LY' },
  { nationality: 'Liechtensteiner', name: 'Liechtenstein', code: 'LI' },
  { nationality: 'Lithuanian', name: 'Lithuania', code: 'LT' },
  { nationality: 'Luxembourgish', name: 'Luxembourg', code: 'LU' },
  { nationality: 'Macedonian', name: 'North Macedonia', code: 'MK' },
  { nationality: 'Malagasy', name: 'Madagascar', code: 'MG' },
  { nationality: 'Malawian', name: 'Malawi', code: 'MW' },
  { nationality: 'Malaysian', name: 'Malaysia', code: 'MY' },
  { nationality: 'Maldivian', name: 'Maldives', code: 'MV' },
  { nationality: 'Malian', name: 'Mali', code: 'ML' },
  { nationality: 'Maltese', name: 'Malta', code: 'MT' },
  { nationality: 'Marshallese', name: 'Marshall Islands', code: 'MH' },
  { nationality: 'Mauritanian', name: 'Mauritania', code: 'MR' },
  { nationality: 'Mauritian', name: 'Mauritius', code: 'MU' },
  { nationality: 'Mexican', name: 'Mexico', code: 'MX' },
  { nationality: 'Micronesian', name: 'Micronesia', code: 'FM' },
  { nationality: 'Moldovan', name: 'Moldova', code: 'MD' },
  { nationality: 'Monegasque', name: 'Monaco', code: 'MC' },
  { nationality: 'Mongolian', name: 'Mongolia', code: 'MN' },
  { nationality: 'Moroccan', name: 'Morocco', code: 'MA' },
  { nationality: 'Mozambican', name: 'Mozambique', code: 'MZ' },
  { nationality: 'Burmese', name: 'Myanmar', code: 'MM' },
  { nationality: 'Namibian', name: 'Namibia', code: 'NA' },
  { nationality: 'Nauruan', name: 'Nauru', code: 'NR' },
  { nationality: 'Nepali', name: 'Nepal', code: 'NP' },
  { nationality: 'Dutch', name: 'Netherlands', code: 'NL' },
  { nationality: 'New Zealander', name: 'New Zealand', code: 'NZ' },
  { nationality: 'Nicaraguan', name: 'Nicaragua', code: 'NI' },
  { nationality: 'Nigerien', name: 'Niger', code: 'NE' },
  { nationality: 'Nigerian', name: 'Nigeria', code: 'NG' },
  { nationality: 'Norwegian', name: 'Norway', code: 'NO' },
  { nationality: 'Omani', name: 'Oman', code: 'OM' },
  { nationality: 'Pakistani', name: 'Pakistan', code: 'PK' },
  { nationality: 'Palauan', name: 'Palau', code: 'PW' },
  { nationality: 'Palestine', name: 'Palestinian', code: 'PS' },
  { nationality: 'Panamanian', name: 'Panama', code: 'PA' },
  { nationality: 'Papua New Guinean', name: 'Papua New Guinea', code: 'PG' },
  { nationality: 'Paraguayan', name: 'Paraguay', code: 'PY' },
  { nationality: 'Peruvian', name: 'Peru', code: 'PE' },
  { nationality: 'Filipino', name: 'Philippines', code: 'PH' },
  { nationality: 'Polish', name: 'Poland', code: 'PL' },
  { nationality: 'Portuguese', name: 'Portugal', code: 'PT' },
  { nationality: 'Qatari', name: 'Qatar', code: 'QA' },
  { nationality: 'Romanian', name: 'Romania', code: 'RO' },
  { nationality: 'Russian', name: 'Russia', code: 'RU' },
  { nationality: 'Rwandan', name: 'Rwanda', code: 'RW' },
  { nationality: 'Kittitian and Nevisian', name: 'Saint Kitts and Nevis', code: 'KN' },
  { nationality: 'Saint Lucian', name: 'Saint Lucia', code: 'LC' },
  { nationality: 'Vincentian', name: 'Saint Vincent and the Grenadines', code: 'VC' },
  { nationality: 'Samoan', name: 'Samoa', code: 'WS' },
  { nationality: 'Sammarinese', name: 'San Marino', code: 'SM' },
  { nationality: 'São Toméan', name: 'Sao Tome and Principe', code: 'ST' },
  { nationality: 'Saudi Arabian', name: 'Saudi Arabia', code: 'SA' },
  { nationality: 'Senegalese', name: 'Senegal', code: 'SN' },
  { nationality: 'Seychellois', name: 'Seychelles', code: 'SC' },
  { nationality: 'Sierra Leonean', name: 'Sierra Leone', code: 'SL' },
  { nationality: 'Singaporean', name: 'Singapore', code: 'SG' },
  { nationality: 'Slovak', name: 'Slovakia', code: 'SK' },
  { nationality: 'Slovenian', name: 'Slovenia', code: 'SI' },
  { nationality: 'Solomon Islander', name: 'Solomon Islands', code: 'SB' },
  { nationality: 'Somali', name: 'Somalia', code: 'SO' },
  { nationality: 'South African', name: 'South Africa', code: 'ZA' },
  { nationality: 'Spanish', name: 'Spain', code: 'ES' },
  { nationality: 'Sri Lankan', name: 'Sri Lanka', code: 'LK' },
  { nationality: 'South Sudanese', name: 'Sudan', code: 'SD' },
  { nationality: 'Surinamese', name: 'Suriname', code: 'SR' },
  { nationality: 'Swazi', name: 'Swaziland', code: 'SZ' },
  { nationality: 'Swedish', name: 'Sweden', code: 'SE' },
  { nationality: 'Swiss', name: 'Switzerland', code: 'CH' },
  { nationality: 'Syrian', name: 'Syria', code: 'SY' },
  { nationality: 'Taiwanese', name: 'Taiwan', code: 'TW' },
  { nationality: 'Tajikistani', name: 'Tajikistan', code: 'TJ' },
  { nationality: 'Tanzanian', name: 'Tanzania', code: 'TZ' },
  { nationality: 'Thai', name: 'Thailand', code: 'TH' },
  { nationality: 'Timorese', name: 'Timor-Leste', code: 'TL' },
  { nationality: 'Togolese', name: 'Togo', code: 'TG' },
  { nationality: 'Tongan', name: 'Tonga', code: 'TO' },
  { nationality: 'Trinidadian and Tobagonian', name: 'Trinidad and Tobago', code: 'TT' },
  { nationality: 'Tunisian', name: 'Tunisia', code: 'TN' },
  { nationality: 'Turkish', name: 'Turkey', code: 'TR' },
  { nationality: 'Turkmen', name: 'Turkmenistan', code: 'TM' },
  { nationality: 'Tuvaluan', name: 'Tuvalu', code: 'TV' },
  { nationality: 'Ugandan', name: 'Uganda', code: 'UG' },
  { nationality: 'Ukrainian', name: 'Ukraine', code: 'UA' },
  { nationality: 'Emirati', name: 'United Arab Emirates', code: 'AE' },
  { nationality: 'British', name: 'United Kingdom', code: 'GB' },
  { nationality: 'American', name: 'United States', code: 'US' },
  { nationality: 'Uruguayan', name: 'Uruguay', code: 'UY' },
  { nationality: 'Uzbek', name: 'Uzbekistan', code: 'UZ' },
  { nationality: 'Ni-Vanuatu', name: 'Vanuatu', code: 'VU' },
  { nationality: 'Venezuelan', name: 'Venezuela', code: 'VE' },
  { nationality: 'Vietnamese', name: 'Vietnam', code: 'VN' },
  { nationality: 'Yemeni', name: 'Yemen', code: 'YE' },
  { nationality: 'Zambian', name: 'Zambia', code: 'ZM' },
  { nationality: 'Zimbabwean', name: 'Zimbabwe', code: 'ZW' },
];

export default countryList;
