const beneficiary = {
  GET_NON_ACMIS_BENEFICIARY_REQUEST: "GET_NON_ACMIS_BENEFICIARY_REQUEST",
  GET_NON_ACMIS_BENEFICIARY_SUCCESS: "GET_NON_ACMIS_BENEFICIARY_SUCCESS",
  GET_NON_ACMIS_BENEFICIARY_ERROR: "GET_NON_ACMIS_BENEFICIARY_ERROR",

  CREATE_ACMIS_BENEFICIARY_REQUEST: "CREATE_ACMIS_BENEFICIARY_REQUEST",
  CREATE_ACMIS_BENEFICIARY_SUCCESS: "CREATE_ACMIS_BENEFICIARY_SUCCESS",
  CREATE_ACMIS_BENEFICIARY_ERROR: "CREATE_ACMIS_BENEFICIARY_ERROR",

  GET_ACMIS_BENEFICIARIES_REQUEST: "GET_ACMIS_BENEFICIARIES_REQUEST",
  GET_ACMIS_BENEFICIARIES_SUCCESS: "GET_ACMIS_BENEFICIARIES_SUCCESS",
  GET_ACMIS_BENEFICIARIES_ERROR: "GET_ACMIS_BENEFICIARIES_ERROR",

  GET_TAX_CODE_BENEFICIARIES_REQUEST: "GET_TAX_CODE_BENEFICIARIES_REQUEST",
  GET_TAX_CODE_BENEFICIARIES_SUCCESS: "GET_TAX_CODE_BENEFICIARIES_SUCCESS",
  GET_TAX_CODE_BENEFICIARIES_ERROR: "GET_TAX_CODE_BENEFICIARIES_ERROR",

  GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_REQUEST:
    "GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_REQUEST",
  GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_SUCCESS:
    "GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_SUCCESS",
  GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_ERROR:
    "GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_ERROR",

  GET_SEARCHED_BENEFICIARIES_REQUEST: "GET_SEARCHED_BENEFICIARIES_REQUEST",
  GET_SEARCHED_BENEFICIARIES_SUCCESS: "GET_SEARCHED_BENEFICIARIES_SUCCESS",
  GET_SEARCHED_BENEFICIARIES_ERROR: "GET_SEARCHED_BENEFICIARIES_ERROR",

  CREATE_NON_ACMIS_BENEFICIARY_REQUEST: "CREATE_NON_ACMIS_BENEFICIARY_REQUEST",
  CREATE_NON_ACMIS_BENEFICIARY_SUCCESS: "CREATE_NON_ACMIS_BENEFICIARY_SUCCESS",
  CREATE_NON_ACMIS_BENEFICIARY_ERROR: "CREATE_NON_ACMIS_BENEFICIARY_ERROR",

  UPDATE_BENEFICIARY_ATTACHMENTS_REQUEST:
    "UPDATE_BENEFICIARY_ATTACHMENTS_REQUEST",
  UPDATE_BENEFICIARY_ATTACHMENTS_SUCCESS:
    "UPDATE_BENEFICIARY_ATTACHMENTS_SUCCESS",
  UPDATE_BENEFICIARY_ATTACHMENTS_ERROR: "UPDATE_BENEFICIARY_ATTACHMENTS_ERROR",

  UPDATE_NON_ACMIS_BENE_AVATAR_REQUEST: "UPDATE_NON_ACMIS_BENE_AVATAR_REQUEST",
  UPDATE_NON_ACMIS_BENE_AVATAR_SUCCESS: "UPDATE_NON_ACMIS_BENE_AVATAR_SUCCESS",
  UPDATE_NON_ACMIS_BENE_AVATAR_ERROR: "UPDATE_NON_ACMIS_BENE_AVATAR_ERROR",

  UPDATE_NON_ACMIS_BENEFICIARY_REQUEST: "UPDATE_NON_ACMIS_BENEFICIARY_REQUEST",
  UPDATE_NON_ACMIS_BENEFICIARY_SUCCESS: "UPDATE_NON_ACMIS_BENEFICIARY_SUCCESS",
  UPDATE_NON_ACMIS_BENEFICIARY_ERROR: "UPDATE_NON_ACMIS_BENEFICIARY_ERROR",

  ADD_BENEFICIARY_ALLOCATIONS_REQUEST: "ADD_BENEFICIARY_ALLOCATIONS_REQUEST",
  ADD_BENEFICIARY_ALLOCATIONS_SUCCESS: "ADD_BENEFICIARY_ALLOCATIONS_SUCCESS",
  ADD_BENEFICIARY_ALLOCATIONS_ERROR: "ADD_BENEFICIARY_ALLOCATIONS_ERROR",

  ADD_ALLOCATION_PAYMENT_REQUEST: "ADD_ALLOCATION_PAYMENT_REQUEST",
  ADD_ALLOCATION_PAYMENT_SUCCESS: "ADD_ALLOCATION_PAYMENT_SUCCESS",
  ADD_ALLOCATION_PAYMENT_ERROR: "ADD_ALLOCATION_PAYMENT_ERROR",

  GET_NON_ACMIS_BENEFICIARIES_REQUEST: "GET_NON_ACMIS_BENEFICIARIES_REQUEST",
  GET_NON_ACMIS_BENEFICIARIES_SUCCESS: "GET_NON_ACMIS_BENEFICIARIES_SUCCESS",
  GET_NON_ACMIS_BENEFICIARIES_ERROR: "GET_NON_ACMIS_BENEFICIARIES_ERROR",

  GET_CONTEXT_BENEFICIARIES_REQUEST: "GET_CONTEXT_BENEFICIARIES_REQUEST",
  GET_CONTEXT_BENEFICIARIES_SUCCESS: "GET_CONTEXT_BENEFICIARIES_SUCCESS",
  GET_CONTEXT_BENEFICIARIES_ERROR: "GET_CONTEXT_BENEFICIARIES_ERROR",

  SEARCH_SYSTEM_BENEFICIARY_REQUEST: "SEARCH_SYSTEM_BENEFICIARY_REQUEST",
  SEARCH_SYSTEM_BENEFICIARY_SUCCESS: "SEARCH_SYSTEM_BENEFICIARY_SUCCESS",
  SEARCH_SYSTEM_BENEFICIARY_ERROR: "SEARCH_SYSTEM_BENEFICIARY_ERROR",

  GET_INST_SYSTEM_DASHBOARD_REQUEST: "GET_INST_SYSTEM_DASHBOARD_REQUEST",
  GET_INST_SYSTEM_DASHBOARD_SUCCESS: "GET_INST_SYSTEM_DASHBOARD_SUCCESS",
  GET_INST_SYSTEM_DASHBOARD_ERROR: "GET_INST_SYSTEM_DASHBOARD_ERROR",

  GET_SYSTEM_DASHBOARD_REQUEST: "GET_SYSTEM_DASHBOARD_REQUEST",
  GET_SYSTEM_DASHBOARD_SUCCESS: "GET_SYSTEM_DASHBOARD_SUCCESS",
  GET_SYSTEM_DASHBOARD_ERROR: "GET_SYSTEM_DASHBOARD_ERROR",

  DOWNLOAD_RESULTS_TEMPLATE_REQUEST: "DOWNLOAD_RESULTS_TEMPLATE_REQUEST",
  DOWNLOAD_RESULTS_TEMPLATE_SUCCESS: "DOWNLOAD_RESULTS_TEMPLATE_SUCCESS",
  DOWNLOAD_RESULTS_TEMPLATE_ERROR: "DOWNLOAD_RESULTS_TEMPLATE_ERROR",

  UPLOAD_RESULTS_TEMPLATE_REQUEST: "UPLOAD_RESULTS_TEMPLATE_REQUEST",
  UPLOAD_RESULTS_TEMPLATE_SUCCESS: "UPLOAD_RESULTS_TEMPLATE_SUCCESS",
  UPLOAD_RESULTS_TEMPLATE_ERROR: "UPLOAD_RESULTS_TEMPLATE_ERROR",

  DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST:
    "DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST",
  DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_SUCCESS:
    "DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_SUCCESS",
  DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_ERROR:
    "DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_ERROR",

  UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST:
    "UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST",
  UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_SUCCESS:
    "UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_SUCCESS",
  UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_ERROR:
    "UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_ERROR",

  DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST:
    "DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST",
  DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_SUCCESS:
    "DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_SUCCESS",
  DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_ERROR:
    "DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_ERROR",

  UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST:
    "UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST",
  UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_SUCCESS:
    "UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_SUCCESS",
  UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_ERROR:
    "UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_ERROR",

  ADD_NON_ACMIS_PAYMENTS_REQUEST: "ADD_NON_ACMIS_PAYMENTS_REQUEST",
  ADD_NON_ACMIS_PAYMENTS_SUCCESS: "ADD_NON_ACMIS_PAYMENTS_SUCCESS",
  ADD_NON_ACMIS_PAYMENTS_ERROR: "ADD_NON_ACMIS_PAYMENTS_ERROR",

  FETCH_PENDING_BENEFICIARIES_REQUEST: "FETCH_PENDING_BENEFICIARIES_REQUEST",
  FETCH_PENDING_BENEFICIARIES_SUCCESS: "FETCH_PENDING_BENEFICIARIES_SUCCESS",
  FETCH_PENDING_BENEFICIARIES_ERROR: "FETCH_PENDING_BENEFICIARIES_ERROR",

  FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_REQUEST:
    "FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_REQUEST",
  FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_SUCCESS:
    "FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_SUCCESS",
  FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_ERROR:
    "FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_ERROR",

  FETCH_PENDING_PAYMENTS_REQUEST: "FETCH_PENDING_PAYMENTS_REQUEST",
  FETCH_PENDING_PAYMENTS_SUCCESS: "FETCH_PENDING_PAYMENTS_SUCCESS",
  FETCH_PENDING_PAYMENTS_ERROR: "FETCH_PENDING_PAYMENTS_ERROR",

  FETCH_PENDING_ALLOCATIONS_REQUEST: "FETCH_PENDING_ALLOCATIONS_REQUEST",
  FETCH_PENDING_ALLOCATIONS_SUCCESS: "FETCH_PENDING_ALLOCATIONS_SUCCESS",
  FETCH_PENDING_ALLOCATIONS_ERROR: "FETCH_PENDING_ALLOCATIONS_ERROR",

  APPROVE_BENEFICIARIES_REQUEST: "APPROVE_BENEFICIARIES_REQUEST",
  APPROVE_BENEFICIARIES_SUCCESS: "APPROVE_BENEFICIARIES_SUCCESS",
  APPROVE_BENEFICIARIES_ERROR: "APPROVE_BENEFICIARIES_ERROR",

  FINAL_BENEFICIARIES_APPROVE_REQUEST: "FINAL_BENEFICIARIES_APPROVE_REQUEST",
  FINAL_BENEFICIARIES_APPROVE_SUCCESS: "FINAL_BENEFICIARIES_APPROVE_SUCCESS",
  FINAL_BENEFICIARIES_APPROVE_ERROR: "FINAL_BENEFICIARIES_APPROVE_ERROR",

  APPROVE_PAYMENTS_REQUEST: "APPROVE_PAYMENTS_REQUEST",
  APPROVE_PAYMENTS_SUCCESS: "APPROVE_PAYMENTS_SUCCESS",
  APPROVE_PAYMENTS_ERROR: "APPROVE_PAYMENTS_ERROR",

  APPROVE_ALLOCATIONS_REQUEST: "APPROVE_ALLOCATIONS_REQUEST",
  APPROVE_ALLOCATIONS_SUCCESS: "APPROVE_ALLOCATIONS_SUCCESS",
  APPROVE_ALLOCATIONS_ERROR: "APPROVE_ALLOCATIONS_ERROR",

  FETCH_BENEFICIARY_RESULTS_REQUEST: "FETCH_BENEFICIARY_RESULTS_REQUEST",
  FETCH_BENEFICIARY_RESULTS_SUCCESS: "FETCH_BENEFICIARY_RESULTS_SUCCESS",
  FETCH_BENEFICIARY_RESULTS_ERROR: "FETCH_BENEFICIARY_RESULTS_ERROR",

  FETCH_ENROLLMENT_TYPE_REPORT_REQUEST: "FETCH_ENROLLMENT_TYPE_REPORT_REQUEST",
  FETCH_ENROLLMENT_TYPE_REPORT_SUCCESS: "FETCH_ENROLLMENT_TYPE_REPORT_SUCCESS",
  FETCH_ENROLLMENT_TYPE_REPORT_ERROR: "FETCH_ENROLLMENT_TYPE_REPORT_ERROR",

  FETCH_SYSTEM_REPORTS_REQUEST: "FETCH_SYSTEM_REPORTS_REQUEST",
  FETCH_SYSTEM_REPORTS_SUCCESS: "FETCH_SYSTEM_REPORTS_SUCCESS",
  FETCH_SYSTEM_REPORTS_ERROR: "FETCH_SYSTEM_REPORTS_ERROR",

  FETCH_INSTITUTION_BENEFICIARIES_REQUEST:
    "FETCH_INSTITUTION_BENEFICIARIES_REQUEST",
  FETCH_INSTITUTION_BENEFICIARIES_SUCCESS:
    "FETCH_INSTITUTION_BENEFICIARIES_SUCCESS",
  FETCH_INSTITUTION_BENEFICIARIES_ERROR:
    "FETCH_INSTITUTION_BENEFICIARIES_ERROR",

  SET_CREATE_BENEFICIARY_FORM: "SET_CREATE_BENEFICIARY_FORM",
  SET_BENEFICIARY_CONTEXT: "SET_BENEFICIARY_CONTEXT",
  SET_SELECTED_ALLOCATION: "SET_SELECTED_ALLOCATION",
  SET_SHOW_PAY_FORM: "SET_SHOW_PAY_FORM",
  SET_FORM_DATA_TO_SEND: "SET_FORM_DATA_TO_SEND",
  SET_DASHBOARD_YEAR: "SET_DASHBOARD_YEAR",
  SET_DASHBOARD_INSTITUTION: "SET_DASHBOARD_INSTITUTION",
  SET_TAX_CODE_CONTEXT: "SET_TAX_CODE_CONTEXT",
  SET_SELECTED_BENEFICIARY: "SET_SELECTED_BENEFICIARY",
  SET_SHOW_BENEFICIARY_MODAL: "SET_SHOW_BENEFICIARY_MODAL",
  SET_SELECTED_INSTITUTION_REPORT: "SET_SELECTED_INSTITUTION_REPORT",
  SET_SELECTED_INST_TYPE_REPORT: "SET_SELECTED_INST_TYPE_REPORT",
  SET_SUPPORT_ITEMS_REPORT: "SET_SUPPORT_ITEMS_REPORT",
  SET_INSTITUTIONS_REPORT: "SET_INSTITUTIONS_REPORT",
  SET_UNFILTERED_STATE_DATA: "SET_UNFILTERED_STATE_DATA",
  SET_BENEFICIARY_SEARCH_PARAM: "SET_BENEFICIARY_SEARCH_PARAM",
  SET_SEARCH_VALIDATION_ERRORS: "SET_SEARCH_VALIDATION_ERRORS",
  SET_SELECTED_INSTITUTION_TYPE: "SET_SELECTED_INSTITUTION_TYPE",
  SET_SELECTED_INST_BENEFICIARIES: "SET_SELECTED_INST_BENEFICIARIES",

  FETCH_ACMIS_STUDENT_REQUEST: "FETCH_ACMIS_STUDENT_REQUEST",

  getNonAcmisBeneficiary: (id, instId) => ({
    type: beneficiary.GET_NON_ACMIS_BENEFICIARY_REQUEST,
    instId,
    id,
  }),

  createAcmisBeneficiary: (data) => ({
    type: beneficiary.CREATE_ACMIS_BENEFICIARY_REQUEST,
    data,
  }),

  getAcmisBeneficiaries: () => ({
    type: beneficiary.GET_ACMIS_BENEFICIARIES_REQUEST,
  }),

  getTaxCodeBeneficiaries: (code) => ({
    type: beneficiary.GET_TAX_CODE_BENEFICIARIES_REQUEST,
    code,
  }),

  getTaxCodeAcadYrBeneficiaries: (code, acadYr, student, searchParam) => ({
    type: beneficiary.GET_TAX_CODE_ACAD_YEAR_BENEFICIARIES_REQUEST,
    code,
    acadYr,
    student,
    searchParam,
  }),

  getAcmisSearchBeneficiaries: (code, student, acadYr, searchParam) => ({
    type: beneficiary.GET_SEARCHED_BENEFICIARIES_REQUEST,
    code,
    student,
    acadYr,
    searchParam,
  }),

  getNonAcmisBeneficiaries: () => ({
    type: beneficiary.GET_NON_ACMIS_BENEFICIARIES_REQUEST,
  }),

  fetchContextBeneficiaries: (data) => ({
    type: beneficiary.GET_CONTEXT_BENEFICIARIES_REQUEST,
    data,
  }),

  searchNonAcmisBeneficiary: (data) => ({
    type: beneficiary.SEARCH_SYSTEM_BENEFICIARY_REQUEST,
    data,
  }),

  fetchSystemDashboard: (year) => ({
    type: beneficiary.GET_SYSTEM_DASHBOARD_REQUEST,
    year,
  }),

  fetchInstSystemDashboard: (institutionId) => ({
    type: beneficiary.GET_INST_SYSTEM_DASHBOARD_REQUEST,
    institutionId,
  }),

  setDashboardInstitution: (institutionId) => ({
    type: beneficiary.SET_DASHBOARD_INSTITUTION,
    institutionId,
  }),

  setDashboardYear: (year) => ({
    type: beneficiary.SET_DASHBOARD_YEAR,
    year,
  }),

  setTaxCodeContext: (context) => ({
    type: beneficiary.SET_TAX_CODE_CONTEXT,
    context,
  }),

  setSelectedBeneficiary: (payload) => ({
    type: beneficiary.SET_SELECTED_BENEFICIARY,
    payload,
  }),

  setShowBeneficiaryModal: (payload) => ({
    type: beneficiary.SET_SHOW_BENEFICIARY_MODAL,
    payload,
  }),

  createNonAcmisBeneficiary: (data) => ({
    type: beneficiary.CREATE_NON_ACMIS_BENEFICIARY_REQUEST,
    data,
  }),

  updateBeneficiaryAttachments: (data, instId, Id) => ({
    type: beneficiary.UPDATE_BENEFICIARY_ATTACHMENTS_REQUEST,
    instId,
    data,
    Id,
  }),

  updateNonAcmisBeneficiary: (id, data, instId) => ({
    type: beneficiary.UPDATE_NON_ACMIS_BENEFICIARY_REQUEST,
    id,
    data,
    instId,
  }),

  addBeneficiaryAllocations: (data, context) => ({
    type: beneficiary.ADD_BENEFICIARY_ALLOCATIONS_REQUEST,
    context,
    data,
  }),

  addAllocationPayment: (data, context) => ({
    type: beneficiary.ADD_ALLOCATION_PAYMENT_REQUEST,
    context,
    data,
  }),

  downloadNonAcmisBeneficiariesTemplate: () => ({
    type: beneficiary.DOWNLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST,
  }),

  downloadResultsTemplate: (context) => ({
    type: beneficiary.DOWNLOAD_RESULTS_TEMPLATE_REQUEST,
    context,
  }),

  uploadResultsTemplate: (data) => ({
    type: beneficiary.UPLOAD_RESULTS_TEMPLATE_REQUEST,
    data,
  }),

  downloadNonAcmisPaymentsTemplate: () => ({
    type: beneficiary.DOWNLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST,
  }),

  uploadNonAcmisPaymentsTemplate: (data) => ({
    type: beneficiary.UPLOAD_NON_ACMIS_PAYMENTS_TEMPLATE_REQUEST,
    data,
  }),

  uploadNonAcmisBeneficiariesTemplate: (data) => ({
    type: beneficiary.UPLOAD_NON_ACMIS_BENEFICIARIES_TEMPLATE_REQUEST,
    data,
  }),

  addNonAcmisPayments: (payload) => ({
    type: beneficiary.ADD_NON_ACMIS_PAYMENTS_REQUEST,
    payload,
  }),

  fetchPendingBeneficiaries: () => ({
    type: beneficiary.FETCH_PENDING_BENEFICIARIES_REQUEST,
  }),

  fetchBeneficiariesPendingFinalApproval: () => ({
    type: beneficiary.FETCH_BENEFICIARIES_PENDING_FINAL_APPROVAL_REQUEST,
  }),

  fetchPendingPayments: () => ({
    type: beneficiary.FETCH_PENDING_PAYMENTS_REQUEST,
  }),

  fetchPendingAllocations: () => ({
    type: beneficiary.FETCH_PENDING_ALLOCATIONS_REQUEST,
  }),

  approveBeneficiaries: (data) => ({
    type: beneficiary.APPROVE_BENEFICIARIES_REQUEST,
    data,
  }),

  finalBeneficiariesApproval: (data) => ({
    type: beneficiary.FINAL_BENEFICIARIES_APPROVE_REQUEST,
    data,
  }),

  approvePendingPayments: (data) => ({
    type: beneficiary.APPROVE_PAYMENTS_REQUEST,
    data,
  }),

  approvePendingAllocations: (data) => ({
    type: beneficiary.APPROVE_ALLOCATIONS_REQUEST,
    data,
  }),

  fetchBeneficiaryResults: (instCode, studentNo) => ({
    type: beneficiary.FETCH_BENEFICIARY_RESULTS_REQUEST,
    instCode,
    studentNo,
  }),

  fetchSystemReports: () => ({
    type: beneficiary.FETCH_SYSTEM_REPORTS_REQUEST,
  }),

  fetchInstitutionBeneficiaries: (data) => ({
    type: beneficiary.FETCH_INSTITUTION_BENEFICIARIES_REQUEST,
    data,
  }),

  fetchEnrollmentTypeReport: (
    code,
    acadYr,
    enrollmentType,
    enrollmentStatus
  ) => ({
    type: beneficiary.FETCH_ENROLLMENT_TYPE_REPORT_REQUEST,
    enrollmentStatus,
    enrollmentType,
    acadYr,
    code,
  }),

  setUnfilteredStateData: (data) => ({
    type: beneficiary.SET_UNFILTERED_STATE_DATA,
    data,
  }),

  setSearchParam: (data) => ({
    type: beneficiary.SET_BENEFICIARY_SEARCH_PARAM,
    data,
  }),

  searchSearchError: (error) => ({
    type: beneficiary.SET_SEARCH_VALIDATION_ERRORS,
    error,
  }),

  selectedInstitutionType: (data) => ({
    type: beneficiary.SET_SELECTED_INSTITUTION_TYPE,
    data,
  }),

  setSelectedInstBeneficiaries: (data) => ({
    type: beneficiary.SET_SELECTED_INST_BENEFICIARIES,
    data,
  }),

  setCreateBeneficiaryForm: (payload) => ({
    type: beneficiary.SET_CREATE_BENEFICIARY_FORM,
    payload,
  }),

  setFormDataToSend: (payload) => ({
    type: beneficiary.SET_FORM_DATA_TO_SEND,
    payload,
  }),

  setBeneficiaryContext: (payload) => {
    return {
      type: beneficiary.SET_BENEFICIARY_CONTEXT,
      payload,
    };
  },

  setSelectedAllocation: (payload) => {
    return {
      type: beneficiary.SET_SELECTED_ALLOCATION,
      payload,
    };
  },

  setShowPayForm: (payload) => {
    return {
      type: beneficiary.SET_SHOW_PAY_FORM,
      payload,
    };
  },

  setSelectedReportInst: (payload) => {
    return {
      type: beneficiary.SET_SELECTED_INSTITUTION_REPORT,
      payload,
    };
  },

  setSelectedReportInstType: (payload) => {
    return {
      type: beneficiary.SET_SELECTED_INST_TYPE_REPORT,
      payload,
    };
  },

  setInstitutionsReport: (payload) => {
    return {
      type: beneficiary.SET_INSTITUTIONS_REPORT,
      payload,
    };
  },

  setSupportItemsReport: (payload) => {
    return {
      type: beneficiary.SET_SUPPORT_ITEMS_REPORT,
      payload,
    };
  },

  // To Delete, it is absolute in the new version
  fetchAcmisStudent: (data) => ({
    type: beneficiary.FETCH_ACMIS_STUDENT_REQUEST,
    data,
  }),
};

export default beneficiary;
