const institution = {
  CREATE_INSTITUTION_REQUEST: "CREATE_INSTITUTION_REQUEST",
  CREATE_INSTITUTION_SUCCESS: "CREATE_INSTITUTION_SUCCESS",
  CREATE_INSTITUTION_ERROR: "CREATE_INSTITUTION_ERROR",

  UPDATE_INSTITUTION_REQUEST: "UPDATE_INSTITUTION_REQUEST",
  UPDATE_INSTITUTION_SUCCESS: "UPDATE_INSTITUTION_SUCCESS",
  UPDATE_INSTITUTION_ERROR: "UPDATE_INSTITUTION_ERROR",

  FETCH_INSTITUTIONS_REQUEST: "FETCH_INSTITUTIONS_REQUEST",
  FETCH_INSTITUTIONS_SUCCESS: "FETCH_INSTITUTIONS_SUCCESS",
  FETCH_INSTITUTIONS_ERROR: "FETCH_INSTITUTIONS_ERROR",

  UPLOAD_INSTITUTIONS_TEMPLATE_REQUEST: "UPLOAD_INSTITUTIONS_TEMPLATE_REQUEST",
  UPLOAD_INSTITUTIONS_TEMPLATE_SUCCESS: "UPLOAD_INSTITUTIONS_TEMPLATE_SUCCESS",
  UPLOAD_INSTITUTIONS_TEMPLATE_ERROR: "UPLOAD_INSTITUTIONS_TEMPLATE_ERROR",

  ADD_SUPPORT_ITEMS_REQUEST: "ADD_SUPPORT_ITEMS_REQUEST",
  ADD_SUPPORT_ITEMS_SUCCESS: "ADD_SUPPORT_ITEMS_SUCCESS",
  ADD_SUPPORT_ITEMS_ERROR: "ADD_SUPPORT_ITEMS_ERROR",

  ADD_PAYMENT_CYCLES_REQUEST: "ADD_PAYMENT_CYCLES_REQUEST",
  ADD_PAYMENT_CYCLES_SUCCESS: "ADD_PAYMENT_CYCLES_SUCCESS",
  ADD_PAYMENT_CYCLES_ERROR: "ADD_PAYMENT_CYCLES_ERROR",

  ADD_STUDY_CLASSES_REQUEST: "ADD_STUDY_CLASSES_REQUEST",
  ADD_STUDY_CLASSES_SUCCESS: "ADD_STUDY_CLASSES_SUCCESS",
  ADD_STUDY_CLASSES_ERROR: "ADD_STUDY_CLASSES_ERROR",

  DELETE_SUPPORT_ITEM_REQUEST: "DELETE_SUPPORT_ITEM_REQUEST",
  DELETE_SUPPORT_ITEM_SUCCESS: "DELETE_SUPPORT_ITEM_SUCCESS",
  DELETE_SUPPORT_ITEM_ERROR: "DELETE_SUPPORT_ITEM_ERROR",

  DELETE_PAYMENT_CYCLE_REQUEST: "DELETE_PAYMENT_CYCLE_REQUEST",
  DELETE_PAYMENT_CYCLE_SUCCESS: "DELETE_PAYMENT_CYCLE_SUCCESS",
  DELETE_PAYMENT_CYCLE_ERROR: "DELETE_PAYMENT_CYCLE_ERROR",

  DELETE_STUDY_CLASS_REQUEST: "DELETE_STUDY_CLASS_REQUEST",
  DELETE_STUDY_CLASS_SUCCESS: "DELETE_STUDY_CLASS_SUCCESS",
  DELETE_STUDY_CLASS_ERROR: "DELETE_STUDY_CLASS_ERROR",

  GET_SUPPORT_ITEMS_REQUEST: "GET_SUPPORT_ITEMS_REQUEST",
  GET_SUPPORT_ITEMS_SUCCESS: "GET_SUPPORT_ITEMS_SUCCESS",
  GET_SUPPORT_ITEMS_ERROR: "GET_SUPPORT_ITEMS_ERROR",

  GET_PAYMENT_CYCLES_REQUEST: "GET_PAYMENT_CYCLES_REQUEST",
  GET_PAYMENT_CYCLES_SUCCESS: "GET_PAYMENT_CYCLES_SUCCESS",
  GET_PAYMENT_CYCLES_ERROR: "GET_PAYMENT_CYCLES_ERROR",

  GET_STUDY_CLASSES_REQUEST: "GET_STUDY_CLASSES_REQUEST",
  GET_STUDY_CLASSES_SUCCESS: "GET_STUDY_CLASSES_SUCCESS",
  GET_STUDY_CLASSES_ERROR: "GET_STUDY_CLASSES_ERROR",

  DOWNLOAD_INSTITUTIONS_TEMPLATE_REQUEST:
    "DOWNLOAD_INSTITUTIONS_TEMPLATE_REQUEST",
  DOWNLOAD_INSTITUTIONS_TEMPLATE_SUCCESS:
    "DOWNLOAD_INSTITUTIONS_TEMPLATE_SUCCESS",
  DOWNLOAD_INSTITUTIONS_TEMPLATE_ERROR: "DOWNLOAD_INSTITUTIONS_TEMPLATE_ERROR",

  SET_SUPPORT_INSTITUTION: "SET_SUPPORT_INSTITUTION",
  SET_INSTITUTION_TO_EDIT: "SET_INSTITUTION_TO_EDIT",

  createInstitution: (data) => ({
    type: institution.CREATE_INSTITUTION_REQUEST,
    data,
  }),

  updateInstitution: (instId, data) => ({
    type: institution.UPDATE_INSTITUTION_REQUEST,
    instId,
    data,
  }),

  fetchInstitutions: () => ({
    type: institution.FETCH_INSTITUTIONS_REQUEST,
  }),

  downloadInstitutionsTemplate: () => ({
    type: institution.DOWNLOAD_INSTITUTIONS_TEMPLATE_REQUEST,
  }),

  uploadInstitutionsTemplate: (data, roleId) => ({
    type: institution.UPLOAD_INSTITUTIONS_TEMPLATE_REQUEST,
    data,
    roleId,
  }),

  setSupportInstitution: (payload) => ({
    type: institution.SET_SUPPORT_INSTITUTION,
    payload,
  }),

  setInstitutionToEdit: (payload) => ({
    type: institution.SET_INSTITUTION_TO_EDIT,
    payload,
  }),

  addSupportItems: (payload) => ({
    type: institution.ADD_SUPPORT_ITEMS_REQUEST,
    payload: { support_items: payload },
  }),

  addPaymentCycles: (payload) => ({
    type: institution.ADD_PAYMENT_CYCLES_REQUEST,
    payload: { payment_cycles: payload },
  }),

  addStudyClasses: (payload) => ({
    type: institution.ADD_STUDY_CLASSES_REQUEST,
    payload: { study_levels: payload },
  }),

  deleteSupportItem: (itemId) => ({
    type: institution.DELETE_SUPPORT_ITEM_REQUEST,
    itemId,
  }),

  deletePaymentCycle: (itemId) => ({
    type: institution.DELETE_PAYMENT_CYCLE_REQUEST,
    itemId,
  }),

  deleteStudyClass: (itemId) => ({
    type: institution.DELETE_STUDY_CLASS_REQUEST,
    itemId,
  }),

  getSupportItems: () => ({
    type: institution.GET_SUPPORT_ITEMS_REQUEST,
  }),

  getPaymentCycles: () => ({
    type: institution.GET_PAYMENT_CYCLES_REQUEST,
  }),

  getStudyClasses: () => ({
    type: institution.GET_STUDY_CLASSES_REQUEST,
  }),
};

export default institution;
